version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - REDIS_TTL=3600
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
